version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_PYTHON_API_URL=http://localhost:8000
    depends_on:
      - backend
      - python-service
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - PYTHON_SERVICE_URL=http://python-service:8000
    depends_on:
      - postgres
      - python-service
    volumes:
      - ./backend:/app
      - /app/node_modules

  python-service:
    build:
      context: ./python/clothflow_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    volumes:
      - ./python/clothflow_service:/app

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=nyambika
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
