// PostgreSQL-only re-exports from schema.ts

export {
  users,
  companies,
  categories,
  products,
  cartItems,
  orders,
  orderItems,
  favorites,
  tryOnSessions,
  outfitCollections,
  sessionComments,
  reviews,
  subscriptionPlans,
  subscriptions,
  subscriptionPayments,
  agentCommissions,
  notifications,
  userWallets,
  walletPayments,
  paymentSettings,
  emailSubscriptions,
  // Insert schemas
  insertUserSchema,
  insertCompanySchema,
  insertCategorySchema,
  insertProductSchema,
  insertCartItemSchema,
  insertOrderSchema,
  insertOrderItemSchema,
  insertFavoriteSchema,
  insertTryOnSessionSchema,
  insertOutfitCollectionSchema,
  insertSessionCommentSchema,
  insertReviewSchema,
  insertSubscriptionPlanSchema,
  insertSubscriptionSchema,
  insertSubscriptionPaymentSchema,
  insertAgentCommissionSchema,
  insertNotificationSchema,
  insertUserWalletSchema,
  insertWalletPaymentSchema,
  insertPaymentSettingSchema,
  insertEmailSubscriptionSchema,
} from "./schema";

// Types
export type {
  User,
  InsertUser,
  Company,
  InsertCompany,
  Category,
  InsertCategory,
  Product,
  InsertProduct,
  CartItem,
  InsertCartItem,
  Order,
  InsertOrder,
  OrderItem,
  InsertOrderItem,
  Favorite,
  InsertFavorite,
  TryOnSession,
  InsertTryOnSession,
  OutfitCollection,
  InsertOutfitCollection,
  SessionComment,
  InsertSessionComment,
  Review,
  InsertReview,
  SubscriptionPlan,
  InsertSubscriptionPlan,
  Subscription,
  InsertSubscription,
  SubscriptionPayment,
  InsertSubscriptionPayment,
  AgentCommission,
  InsertAgentCommission,
  Notification,
  InsertNotification,
  UserWallet,
  InsertUserWallet,
  WalletPayment,
  InsertWalletPayment,
  PaymentSetting,
  InsertPaymentSetting,
  EmailSubscription,
  InsertEmailSubscription,
} from "./schema";
