// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin-dashboard" | "/admin-users" | "/admin/agent/[agentId]" | "/agent-dashboard" | "/agent/dashboard" | "/agent/producer/[id]/subscription" | "/agent/producers-management" | "/agent/referrals" | "/agent/subscription/renew/[producerId]" | "/auth/oauth-complete" | "/cart" | "/checkout" | "/companies" | "/contact" | "/cookies" | "/help" | "/orders" | "/orders/[id]" | "/outfit-room" | "/privacy" | "/producer-orders" | "/producer-subscription" | "/producer/[producerId]/orders" | "/producer/dashboard" | "/producer/orders" | "/producer/orders/[id]" | "/product-categories" | "/product-edit/[id]" | "/product-registration" | "/product/[id]" | "/products" | "/products-search" | "/profile" | "/public-tryon" | "/register" | "/reset-password" | "/returns" | "/session-details/[id]" | "/size-guide" | "/social-banner" | "/store/[id]" | "/subscription" | "/subscription/manage" | "/subscription/payment/[subscriptionId]" | "/terms" | "/try-on" | "/try-on-history" | "/try-on-widget/[productId]" | "/tryon-room" | "/wallet/transactions"
type AppRouteHandlerRoutes = "/api/contact" | "/api/og/store/[id]" | "/api/pexels/search" | "/api/producers/[id]/presence" | "/api/tryon" | "/api/tryon-room" | "/api/tryon/fetch-image" | "/api/tryon/tryonapi" | "/auth/receive-token"
type PageRoutes = never
type LayoutRoutes = "/" | "/auth/oauth-complete" | "/cart" | "/checkout" | "/companies" | "/orders" | "/orders/[id]" | "/product/[id]" | "/products" | "/products-search" | "/profile" | "/public-tryon" | "/register" | "/session-details/[id]" | "/store/[id]" | "/try-on" | "/try-on-widget/[productId]" | "/tryon-room"
type RedirectRoutes = never
type RewriteRoutes = "/api/tryon"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin-dashboard": {}
  "/admin-users": {}
  "/admin/agent/[agentId]": { "agentId": string; }
  "/agent-dashboard": {}
  "/agent/dashboard": {}
  "/agent/producer/[id]/subscription": { "id": string; }
  "/agent/producers-management": {}
  "/agent/referrals": {}
  "/agent/subscription/renew/[producerId]": { "producerId": string; }
  "/api/contact": {}
  "/api/og/store/[id]": { "id": string; }
  "/api/pexels/search": {}
  "/api/producers/[id]/presence": { "id": string; }
  "/api/tryon": {}
  "/api/tryon-room": {}
  "/api/tryon/fetch-image": {}
  "/api/tryon/tryonapi": {}
  "/auth/oauth-complete": {}
  "/auth/receive-token": {}
  "/cart": {}
  "/checkout": {}
  "/companies": {}
  "/contact": {}
  "/cookies": {}
  "/help": {}
  "/orders": {}
  "/orders/[id]": { "id": string; }
  "/outfit-room": {}
  "/privacy": {}
  "/producer-orders": {}
  "/producer-subscription": {}
  "/producer/[producerId]/orders": { "producerId": string; }
  "/producer/dashboard": {}
  "/producer/orders": {}
  "/producer/orders/[id]": { "id": string; }
  "/product-categories": {}
  "/product-edit/[id]": { "id": string; }
  "/product-registration": {}
  "/product/[id]": { "id": string; }
  "/products": {}
  "/products-search": {}
  "/profile": {}
  "/public-tryon": {}
  "/register": {}
  "/reset-password": {}
  "/returns": {}
  "/session-details/[id]": { "id": string; }
  "/size-guide": {}
  "/social-banner": {}
  "/store/[id]": { "id": string; }
  "/subscription": {}
  "/subscription/manage": {}
  "/subscription/payment/[subscriptionId]": { "subscriptionId": string; }
  "/terms": {}
  "/try-on": {}
  "/try-on-history": {}
  "/try-on-widget/[productId]": { "productId": string; }
  "/tryon-room": {}
  "/wallet/transactions": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/auth/oauth-complete": never
  "/cart": never
  "/checkout": never
  "/companies": never
  "/orders": never
  "/orders/[id]": never
  "/product/[id]": never
  "/products": never
  "/products-search": never
  "/profile": never
  "/public-tryon": never
  "/register": never
  "/session-details/[id]": never
  "/store/[id]": never
  "/try-on": never
  "/try-on-widget/[productId]": never
  "/tryon-room": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
