// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-users">> = Specific
  const handler = {} as typeof import("../../src/app/admin-users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/agent/[agentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agent/[agentId]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/agent/[agentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/agent-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/agent/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/producer/[id]/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/producer/[id]/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/agent/producer/[id]/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/producers-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/producers-management">> = Specific
  const handler = {} as typeof import("../../src/app/agent/producers-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/referrals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/referrals">> = Specific
  const handler = {} as typeof import("../../src/app/agent/referrals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/subscription/renew/[producerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/subscription/renew/[producerId]">> = Specific
  const handler = {} as typeof import("../../src/app/agent/subscription/renew/[producerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/oauth-complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/oauth-complete">> = Specific
  const handler = {} as typeof import("../../src/app/auth/oauth-complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../src/app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies">> = Specific
  const handler = {} as typeof import("../../src/app/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../src/app/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../src/app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../src/app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/outfit-room/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outfit-room">> = Specific
  const handler = {} as typeof import("../../src/app/outfit-room/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/producer-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/producer-orders">> = Specific
  const handler = {} as typeof import("../../src/app/producer-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/producer-subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/producer-subscription">> = Specific
  const handler = {} as typeof import("../../src/app/producer-subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/producer/[producerId]/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/producer/[producerId]/orders">> = Specific
  const handler = {} as typeof import("../../src/app/producer/[producerId]/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/producer/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/producer/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/producer/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/producer/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/producer/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/producer/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/producer/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/producer/orders">> = Specific
  const handler = {} as typeof import("../../src/app/producer/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product-categories">> = Specific
  const handler = {} as typeof import("../../src/app/product-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product-edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product-edit/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/product-edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product-registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product-registration">> = Specific
  const handler = {} as typeof import("../../src/app/product-registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/product/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products-search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products-search">> = Specific
  const handler = {} as typeof import("../../src/app/products-search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/public-tryon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public-tryon">> = Specific
  const handler = {} as typeof import("../../src/app/public-tryon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/returns">> = Specific
  const handler = {} as typeof import("../../src/app/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/session-details/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/session-details/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/session-details/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/size-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/size-guide">> = Specific
  const handler = {} as typeof import("../../src/app/size-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/social-banner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/social-banner">> = Specific
  const handler = {} as typeof import("../../src/app/social-banner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/store/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/store/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subscription/manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription/manage">> = Specific
  const handler = {} as typeof import("../../src/app/subscription/manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subscription/payment/[subscriptionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription/payment/[subscriptionId]">> = Specific
  const handler = {} as typeof import("../../src/app/subscription/payment/[subscriptionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/try-on-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/try-on-history">> = Specific
  const handler = {} as typeof import("../../src/app/try-on-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/try-on-widget/[productId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/try-on-widget/[productId]">> = Specific
  const handler = {} as typeof import("../../src/app/try-on-widget/[productId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/try-on/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/try-on">> = Specific
  const handler = {} as typeof import("../../src/app/try-on/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tryon-room/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tryon-room">> = Specific
  const handler = {} as typeof import("../../src/app/tryon-room/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wallet/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/wallet/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/og/store/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og/store/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/og/store/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pexels/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pexels/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/pexels/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/producers/[id]/presence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/producers/[id]/presence">> = Specific
  const handler = {} as typeof import("../../src/app/api/producers/[id]/presence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tryon-room/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tryon-room">> = Specific
  const handler = {} as typeof import("../../src/app/api/tryon-room/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tryon/fetch-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tryon/fetch-image">> = Specific
  const handler = {} as typeof import("../../src/app/api/tryon/fetch-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tryon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tryon">> = Specific
  const handler = {} as typeof import("../../src/app/api/tryon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tryon/tryonapi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tryon/tryonapi">> = Specific
  const handler = {} as typeof import("../../src/app/api/tryon/tryonapi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/receive-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/receive-token">> = Specific
  const handler = {} as typeof import("../../src/app/auth/receive-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/auth/oauth-complete/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth/oauth-complete">> = Specific
  const handler = {} as typeof import("../../src/app/auth/oauth-complete/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cart/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../src/app/cart/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/companies/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/companies">> = Specific
  const handler = {} as typeof import("../../src/app/companies/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/orders/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../src/app/orders/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/product/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/product/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products-search/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/products-search">> = Specific
  const handler = {} as typeof import("../../src/app/products-search/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/products/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/public-tryon/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/public-tryon">> = Specific
  const handler = {} as typeof import("../../src/app/public-tryon/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/session-details/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/session-details/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/session-details/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/store/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/store/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/store/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/try-on-widget/[productId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/try-on-widget/[productId]">> = Specific
  const handler = {} as typeof import("../../src/app/try-on-widget/[productId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/try-on/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/try-on">> = Specific
  const handler = {} as typeof import("../../src/app/try-on/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tryon-room/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tryon-room">> = Specific
  const handler = {} as typeof import("../../src/app/tryon-room/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
