"use client";

import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

type Language = "en" | "rw" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

interface LanguageProviderProps {
  children: ReactNode;
}

// Basic translations - can be expanded
const translations = {
  en: {
    home: "Home",
    companies: "Companies",
    tryOn: "Try-On",
    products: "Products",
    cart: "Cart",
    profile: "Profile",
    signIn: "Sign In",
    signOut: "Sign Out",
    browse: "Browse",
    myProducts: "My Products",
    addProduct: "Add Product",
    orders: "Orders",
    myOrders: "My Orders",
    myStore: "My Store",
    subscription: "Subscription",
    productCategories: "Product Categories",
    usersManagement: "Users Management",
    dashboard: "Dashboard",
    producersManagement: "Producers Management",
    navigation: "Navigation",
    tools: "Tools",
    account: "Account",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    shoppingCart: "Shopping Cart",
    profileSettings: "Profile Settings",
    changePassword: "Change Password",
    active: "Active",
    expired: "Expired",
    expiringIn: "Expiring in",
    walletBalance: "Wallet Balance",
    loading: "Loading...",
    balance: "Balance",
    manageSubscription: "Manage Subscription",
    activeSubscriptionRequired: "Active subscription required",
    needActiveSubscription:
      "You need an active subscription to create new products.",
    activePlan: "Active plan",
    subscriptionInactive: "Subscription expired or not active",
    productLimitReached: "Product limit reached",
    planAllowsUpTo_prefix: "Your current plan allows up to",
    planAllowsUpTo_suffix:
      "products. Please remove some products or upgrade your plan to add more.",
    newProduct: "New Product",
    createProduct: "Create Product",
    productCreatedTitle: "Product created successfully!",
    productCreatedDesc_prefix: "",
    productCreatedDesc_suffix: " has been submitted for approval.",
    productCreateFailed: "Failed to create product",
    goToDashboard: "Go to Dashboard",
    upgradePlan: "Upgrade Plan",
    readAgain: "Read Again",
    agreeAndContinue: "I Agree & Continue",
    confirming: "Confirming...",
    version: "Version",
    updated: "Updated",
    agentTermsTitle: "Agent Terms & Conditions",
    termsScopeOfWork: "Scope of Work",
    termsScopeContent: "Agents help producers subscribe and process payments.",
    termsCommissionTitle: "40% Commission",
    termsCommissionDesc: "Earn on every subscription you process",
    termsProfessionalConductTitle: "Professional Conduct",
    termsProfessionalConductDesc: "Follow policies and local regulations",
    acceptTermsFailed: "Failed to accept terms. Please try again.",
    producerTermsTitle: "Producer Terms & Conditions",
    verifiedBusiness: "Verified Business",
    verifiedBusinessDesc: "Keep details accurate for trust and visibility",
    timelyFulfillment: "Timely Fulfillment",
    timelyFulfillmentDesc: "Acknowledge and ship orders on time",
    // Pages
    "privacy.title": "Privacy Policy",
    "privacy.subtitle":
      "Learn how we collect, use, and protect your data at Nyambika.",
    "privacy.section1.title": "1. Information We Collect",
    "privacy.section2.title": "2. How We Use Your Information",
    "privacy.section3.title": "3. Data Sharing",
    "privacy.section4.title": "4. Your Rights & Choices",
    "privacy.section5.title": "5. Data Security & Retention",
    "privacy.section6.title": "6. Contact Us",
    "privacy.section1.body":
      "We collect information to provide and improve our services, including account details, device information, usage data, and content you upload (e.g., profile photos for AI try‑on). We minimize collection and store only what is necessary.",
    "privacy.section2.body":
      "We use data to operate Nyambika, deliver personalized experiences, ensure security, and comply with legal obligations.",
    "privacy.section3.body":
      "We do not sell your personal information. We share data only with trusted providers and partners necessary to operate our platform (e.g., hosting, analytics, payment, or content delivery), subject to strict confidentiality and security measures.",
    "privacy.section4.item1": "Access, update, or delete your account data",
    "privacy.section4.item2": "Download your data where applicable",
    "privacy.section4.item3": "Opt out of non-essential communications",
    "privacy.section4.item4": "Control cookies in your browser settings",
    "privacy.section5.body":
      "We use industry-standard security practices. Data is retained only as long as necessary to provide the service or meet legal requirements, after which it is deleted or anonymized.",
    "privacy.section6.body":
      "For privacy questions or requests, reach us at privacy@nyambika.com.",
    "terms.title": "Terms of Service",
    "terms.subtitle":
      "The rules and conditions for using Nyambika and our services.",
    "terms.body.intro":
      "These Terms govern your use of Nyambika. By using our services, you agree to these Terms.",
    "terms.section1.title": "1. Acceptance of Terms",
    "terms.section2.title": "2. Use of the Service",
    "terms.section3.title": "3. AI Try‑On and Content",
    "terms.section4.title": "4. Orders and Marketplace",
    "terms.section5.title": "5. Disclaimers and Liability",
    "terms.section6.title": "6. Changes to Terms",
    "terms.section7.title": "7. Contact",
    "terms.section1.body":
      "By using Nyambika, you agree to these Terms. If you do not agree, please discontinue use of the platform.",
    "terms.section2.item1": "You must provide accurate account information.",
    "terms.section2.item2":
      "Do not misuse the platform, including attempts to disrupt or reverse engineer services.",
    "terms.section2.item3":
      "Respect intellectual property and community guidelines.",
    "terms.section3.body":
      "You retain rights to the photos you upload. You grant Nyambika a limited license to process and display your content solely to provide the service.",
    "terms.section4.body":
      "Orders are placed directly with producers on the platform. Nyambika facilitates discovery and ordering. Payment and fulfillment terms may vary by producer.",
    "terms.section5.body":
      "The service is provided 'as is' without warranties. To the maximum extent permitted by law, Nyambika is not liable for indirect or consequential damages.",
    "terms.section6.body":
      "We may update these Terms from time to time. Material changes will be communicated through the platform or by email.",
    "terms.section7.body":
      "For questions about these Terms, contact legal@nyambika.com.",
    // Contact form
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.message": "Message",
    "contact.form.placeholder.name": "Your name",
    "contact.form.placeholder.email": "you@example.com",
    "contact.form.placeholder.message": "How can we help?",
    "contact.form.send": "Send Message",
    "contact.form.sending": "Sending...",
    "contact.toast.missing.title": "Missing fields",
    "contact.toast.missing.desc": "Please fill in all fields.",
    "contact.toast.invalid.title": "Invalid email",
    "contact.toast.invalid.desc": "Please provide a valid email.",
    "contact.toast.sent.title": "Message sent",
    "contact.toast.sent.desc":
      "Thanks for reaching out! We'll get back to you soon.",
    "contact.toast.failed.title": "Submission failed",
    "contact.toast.failed.desc": "Please try again later.",
    "contact.info.title": "Contact Information",
    // Companies
    "companies.title": "AI Fashion Brands",
    "companies.subtitle": "Rwanda's innovative fashion entrepreneurs",
    "companies.searchPlaceholder": "Search brands...",
    "companies.sort.name": "Name",
    "companies.sort.score": "Score",
    "companies.sort.trending": "Hot",
    "companies.viewStore": "View Store",
    "companies.empty.title": "No brands found",
    "companies.empty.desc": "Try adjusting your search or filters",
    "cookies.title": "Cookie Policy",
    "cookies.subtitle":
      "How we use cookies and similar technologies to improve your experience.",
    "cookies.body.intro":
      "We use cookies to remember your preferences and improve performance.",
    "cookies.section1.title": "1. What Are Cookies?",
    "cookies.section2.title": "2. Types of Cookies We Use",
    "cookies.section3.title": "3. Managing Cookies",
    "cookies.section4.title": "4. Contact",
    "cookies.section1.body":
      "Cookies are small text files stored on your device to remember preferences and improve site performance. We also use similar technologies like local storage and pixels.",
    "cookies.section2.item1":
      "Essential: required for core functionality (auth, cart, navigation)",
    "cookies.section2.item2":
      "Performance: helps us understand usage and improve features",
    "cookies.section2.item3":
      "Preferences: remembers your theme, language, and settings",
    "cookies.section2.item4":
      "Analytics: helps measure engagement and product quality",
    "cookies.section3.body":
      "You can control cookies through your browser settings. Disabling some cookies may affect site functionality.",
    "cookies.section4.body":
      "For questions about this policy, email privacy@nyambika.com.",
    "about.title": "About Nyambika",
    "about.subtitle":
      "We are building the AI-powered fashion platform for Rwanda.",
    "about.body.intro":
      "Nyambika empowers shoppers and producers with AI try-on, storefronts, and analytics.",
    "about.mission": "Mission",
    "about.whatWeDo": "What We Do",
    "about.values": "Values",
    "about.mission.body":
      "Empower Rwanda's fashion ecosystem with accessible AI technology, enabling consumers to visualize styles instantly and helping producers reach customers efficiently.",
    "about.whatWeDo.item1": "AI Try‑On for instant fit visualization",
    "about.whatWeDo.item2": "Modern marketplace for local producers",
    "about.whatWeDo.item3": "Personalized recommendations and search",
    "about.whatWeDo.item4": "Seamless ordering and producer dashboards",
    "about.values.item1": "Privacy & trust",
    "about.values.item2": "Local-first impact",
    "about.values.item3": "Inclusivity & accessibility",
    "about.values.item4": "Quality and craftsmanship",
    "about.getInTouch": "Get in touch",
    "about.quickStats": "Quick Stats",
    "contact.title": "Get in Touch",
    "contact.subtitle":
      "We'd love to hear from you. Send us a message and our team will reply promptly.",
    "contact.body.intro":
      "For questions or requests, contact our team and we'll respond promptly.",
    // Home
    "home.brands": "Brands Stories",
    "home.shopByCategory": "Shop by Category",
    // Footer links
    "footer.link.help": "Help Center",
    "footer.link.sizeGuide": "Size Guide",
    "footer.link.returns": "Returns",
    "footer.whatsappAria": "Chat on WhatsApp",
    "home.trending": "Trending Products",
    "home.hot": "HOT",
    "home.moreTitle": "More Amazing Products Await!",
    "home.moreDesc.prefix": "Discover",
    "home.moreDesc.suffix":
      "+ more incredible products in our full collection. Find your perfect style match!",
    "home.browseAll": "Browse All Products",
    "home.advancedSearch": "Advanced search & filters available",
    "home.noProducts": "No products found",
    "home.noProductsDesc":
      "We couldn't find any products matching your criteria. Try adjusting your filters.",
    "home.clearFilters": "Clear Filters",
    "home.products": "Products",
    "home.items": "items",
    // Products Search
    "search.title": "Discover Products",
    "search.subtitle": "Find amazing products with AI-powered search ✨",
    "search.searchingFor": "Searching for",
    "search.allProducts": "All Products",
    "search.browseAll": "Browse all",
    "search.items": "items",
    "search.products": "products",
    "search.product": "product",
    "search.category": "Category",
    "search.showing": "Showing",
    "search.noProducts": "No products found",
    "search.noProductsFor": "We couldn't find any products matching",
    "search.tryAdjust": "Try adjusting your search or filters.",
    "search.noProductsInCategory": "No products available in this category.",
    "search.clearFilters": "Clear filters",
    "search.loadMore": "Load More",
    "search.loadMoreProducts": "Load More Products",
    "search.loading": "Loading...",
    "search.loadingMore": "Loading more products...",
    "search.sort.newest": "Newest First",
    "search.sort.popular": "Most Popular",
    "search.sort.priceAsc": "Price: Low to High",
    "search.sort.priceDesc": "Price: High to Low",
    "search.error.title": "Something went wrong",
    "search.error.message": "We couldn't load the products. Please try again.",
    "search.error.retry": "Try again",
    // Product Details
    "product.linkCopiedTitle": "Link copied",
    "product.linkCopiedDesc": "Product link copied to clipboard.",
    "product.deleted": "Deleted",
    "product.deletedDesc": "Product deleted successfully.",
    "product.deleteFailed": "Delete failed",
    "product.deleteConfirm": "Delete this product? This cannot be undone.",
    "product.sizeRequired": "Size Required",
    "product.selectSizeFirst": "Please select a size first",
    "product.colorRequired": "Color Required",
    "product.selectColorFirst": "Please select a color first",
    "product.addedToCart": "Added to cart",
    "product.addedToCartDesc": "Product added to your cart",
    "product.notFound": "Product Not Found",
    "product.backToProducts": "Back to Products",
    "product.back": "Back",
    "product.details": "Product Details",
    "product.share": "Share",
    "product.edit": "Edit product",
    "product.boost": "Boost product",
    "product.delete": "Delete product",
    "product.aiReady": "AI Ready",
    "product.inStock": "✓ In Stock",
    "product.outOfStock": "Out of Stock",
    // Cart
    "cart.aiBadge": "AI-Powered Cart",
    "cart.title": "Shopping Cart",
    "cart.emptyTitle": "Empty Cart",
    "cart.emptySubtitle": "Your cart is waiting for amazing products",
    "cart.startShopping": "Start Shopping",
    "cart.size": "Size",
    "cart.total": "Total",
    "cart.submitOrder": "Submit Order",
    "cart.continueShopping": "Continue Shopping",
    // Checkout
    "checkout.backToCart": "Back to Cart",
    "checkout.title": "Checkout",
    "checkout.submittingOverlay": "Submitting your order…",
    "checkout.shippingInfo": "Shipping Information",
    "checkout.fullName": "Full Name *",
    "checkout.email": "Email *",
    "checkout.phone": "Phone Number *",
    "checkout.country": "Country",
    "checkout.address": "Street Address *",
    "checkout.city": "City *",
    "checkout.province": "Province",
    "checkout.postalCode": "Postal Code",
    "checkout.sizeEvidenceTitle": "Size Evidence Photos (Optional)",
    "checkout.sizeEvidenceDesc":
      "Upload up to 2 photos to help the producer understand your size requirements",
    "checkout.orderNotesTitle": "Order Notes (Optional)",
    "checkout.orderNotesPlaceholder":
      "Any special instructions for your order...",
    "checkout.orderSummary": "Order Summary",
    "checkout.subtotal": "Subtotal",
    "checkout.shipping": "Shipping",
    "checkout.total": "Total",
    "checkout.submitting": "Submitting Order...",
    "checkout.submitOrder": "Submit Order",
    "checkout.submitShort": "Submit",
    "checkout.termsNotice":
      "By placing this order, you agree to our Terms of Service and Privacy Policy.",
    "checkout.authRequiredTitle": "Authentication Required",
    "checkout.authRequiredDesc": "Please sign in to proceed with checkout.",
    "checkout.validationErrorsTitle": "Validation errors",
    "checkout.validationErrorsDesc": "Please fix the highlighted fields.",
    "checkout.invalidEmail": "Please enter a valid email",
    "checkout.invalidPhone": "Please enter a valid phone (07XXXXXXXX)",
    // Orders
    "orders.back": "Back",
    "orders.title": "My Orders",
    "orders.aiBadge": "AI-Powered Management",
    "orders.count": "Orders",
    "orders.empty.title": "Your Order Journey Awaits",
    "orders.empty.subtitle":
      "Discover amazing products and start your shopping adventure with AI-powered recommendations.",
    "orders.empty.cta": "Start Shopping",
    "orders.order": "Order",
    "orders.viewDetails": "View Details",
    "orders.receipt": "Receipt",
    "orders.cancel": "Cancel",
    "orders.cancelling": "Cancelling...",
    "orders.shippingAddress": "Shipping Address",
    "orders.itemsLabel": "items • Total quantity",
    "orders.cancelConfirm":
      "Are you sure you want to cancel this order? This action cannot be undone.",
    "orders.cancelled": "Order Cancelled",
    "orders.cancelledDesc": "Your order has been successfully cancelled.",
    "orders.cancelFailed": "Cancellation Failed",
    "orders.receiptDownloaded": "Receipt Downloaded",
    "orders.receiptDownloadedDesc":
      "Your receipt has been downloaded successfully.",
    "orders.receiptFailed": "Download Failed",
    "orders.receiptFailedDesc": "Failed to generate receipt. Please try again.",
    "orders.status.pending": "Pending",
    "orders.status.confirmed": "Confirmed",
    "orders.status.processing": "Processing",
    "orders.status.handled": "Handled",
    "orders.status.shipped": "Shipped",
    "orders.status.delivered": "Delivered",
    "orders.status.cancelled": "Cancelled",
    "orders.status.completed": "Completed",
    // Orders Detail
    "orders.detail.aiTrack": "AI-Powered Tracking",
    "orders.detail.aiTrackShort": "AI Track",
    "orders.detail.journey": "Order Journey",
    "orders.detail.journeyShort": "Journey",
    "orders.detail.complete": "Complete",
    "orders.detail.tracking": "Tracking",
    "orders.detail.orderItems": "Order Items",
    "orders.detail.items": "Items",
    "orders.detail.count": "item",
    "orders.detail.countPlural": "items",
    "orders.detail.size": "Size",
    "orders.detail.color": "Color",
    "orders.detail.each": "each",
    "orders.detail.deliveryAddress": "Delivery Address",
    "orders.detail.addressShort": "Address",
    "orders.detail.aiRoute": "AI-optimized route",
    "orders.detail.orderSummary": "Order Summary",
    "orders.detail.summary": "Summary",
    "orders.detail.itemsLine": "Items ({count})",
    "orders.detail.total": "Total",
    "orders.detail.paymentDetails": "Payment Details",
    "orders.detail.payment": "Payment",
    "orders.detail.method": "Method",
    "orders.detail.status": "Status",
    "orders.detail.orderNotes": "Order Notes",
    "orders.detail.notes": "Notes",
    "orders.detail.leaveReview": "Leave a Review",
    "orders.detail.review": "Review",
    "orders.detail.confirming": "Confirming...",
    "orders.detail.confirmReceived": "Confirm Order Received",
    "orders.detail.confirmReceivedShort": "Confirm Received",
    "orders.detail.confirmedTitle": "Order Confirmed",
    "orders.detail.confirmedDesc":
      "Thank you for confirming that you received your order!",
    "orders.detail.confirmedOn": "Confirmed on",
    "orders.detail.copyOrderId": "Copy Order ID",
    "orders.detail.copyId": "Copy ID",
    "orders.detail.viewAll": "View All Orders",
    "orders.detail.allOrders": "All Orders",
    "orders.detail.continueShopping": "Continue Shopping",
    "orders.detail.shopMore": "Shop More",
    "orders.detail.backToOrders": "Back to Orders",
    "orders.detail.back": "Back",
    "orders.detail.notFoundTitle": "Order Not Found",
    "orders.detail.notFoundDesc":
      "The order you're looking for doesn't exist or you don't have permission to view it.",
    "orders.detail.copied": "Copied to clipboard!",
    "orders.detail.copiedShort": "Copied!",
    "orders.detail.trackingCopied": "Tracking number copied to clipboard",
    "orders.detail.confirmError": "Failed to confirm order. Please try again.",
    // Footer
    "footer.liveBadge": "Live AI",
    "footer.tryOutfits": "Try outfits virtually",
    "footer.ctaTitle": "Experience AI Try‑On for Your Next Look",
    "footer.ctaDesc":
      "Upload your photo, get instant smart fits, and shop confidently with Nyambika’s AI.",
    "footer.startTryOn": "Start AI Try‑On",
    "footer.browseProducts": "Browse Products",
    "footer.brandTagline":
      "AI-powered fashion platform for Rwanda's clothing sector. Discover, try-on, and shop from local producers.",
    "footer.stayUpdated": "Stay Updated",
    "footer.subscribeDesc":
      "Subscribe to get new arrivals, updates and special offers.",
    "footer.invalidEmailTitle": "Invalid email",
    "footer.invalidEmailDesc": "Please enter a valid email address.",
    "footer.alreadySubscribed": "Already subscribed",
    "footer.alreadySubscribedDesc": "This email is already on our list.",
    "footer.subscribed": "Subscribed",
    "footer.subscribedDesc": "Thanks for joining our newsletter!",
    "footer.subscriptionFailed": "Subscription failed",
    "footer.subscriptionFailedDesc": "Please try again later.",
    "footer.emailPlaceholder": "Enter your email",
    "footer.emailAria": "Email address",
    "footer.subscribing": "Subscribing...",
    "footer.subscribe": "Subscribe",
    "footer.chatWhatsApp": "Chat on WhatsApp",
    "footer.phone": "+250 782 634 364",
    "footer.email": "info@nyambika.com",
    "footer.location": "Kigali, Rwanda",
    "footer.copyright": "© {year} Nyambika.",
    "footer.allRights": "All rights reserved.",
    "footer.backToTop": "Back to top",
    "footer.link.home": "Home",
    "footer.link.products": "Products",
    "footer.link.tryOn": "AI Try-On",
    "footer.link.profile": "Profile",
    "footer.link.about": "About",
    "footer.link.contact": "Contact",
    "footer.link.privacy": "Privacy",
    "footer.link.terms": "Terms",
    "footer.link.cookies": "Cookies",
    // Profile
    "profile.title": "Profile Dashboard",
    "profile.subtitle": "Manage your fashion journey and preferences",
    "profile.active": "Active",
    "profile.stats.favorites": "Favorites",
    "profile.stats.orders": "Orders",
    "profile.stats.tryOns": "Try-Ons",
    "profile.stats.matchScore": "Match Score",
    "profile.user.fallback": "User",
    "profile.location.notSet": "Location not set",
    "profile.btn.edit": "Edit",
    "profile.btn.save": "Save",
    "profile.btn.saveChanges": "Save Changes",
    "profile.btn.cancel": "Cancel",
    "profile.quickActions": "Quick Actions",
    "profile.action.tryOn": "Try-On",
    "profile.action.favorites": "Favorites",
    "profile.action.orders": "Orders",
    "profile.recentActivity": "Recent Activity",
    "profile.noRecentOrders": "No recent orders",
    "profile.startShopping": "Start Shopping",
    "profile.toast.updateSuccess.title": "Profile updated successfully!",
    "profile.toast.updateSuccess.desc":
      "Your profile information has been saved.",
    "profile.toast.updateFail.title": "Failed to update profile",
    "profile.toast.updateFail.desc": "Please try again.",
    // Producer Dashboard
    "producer.dashboard.title": "Producer Dashboard",
    "producer.dashboard.subtitle": "Manage orders for Producer {id}",
    "producer.stats.totalOrders": "Total Orders",
    "producer.stats.pending": "Pending",
    "producer.stats.processing": "Processing",
    "producer.stats.completed": "Completed",
    "producer.orders.empty.title": "No Orders Yet",
    "producer.orders.empty.desc": "You don't have any orders to manage.",
    "producer.order": "Order",
    "producer.customer": "Customer",
    "producer.total": "Total",
    "producer.date": "Date",
    "producer.items": "Items",
    "producer.productsOne": "product",
    "producer.productsMany": "products",
    "producer.viewDetails": "View Details",
    "producer.update": "Update",
    "producer.orderDetails": "Order Details",
    "producer.customerInfo": "Customer Information",
    "producer.orderItems": "Order Items",
    "producer.subtotal": "Subtotal",
    "producer.shipping": "Shipping",
    "producer.totalLabel": "Total",
    "producer.updateOrder": "Update Order",
    "producer.status": "Status",
    "producer.notes": "Notes",
    "producer.notesPlaceholder": "Add notes about this order...",
    "producer.updating": "Updating...",
    "producer.cancel": "Cancel",
    "producer.error.title": "Error Loading Orders",
    "producer.error.desc": "Failed to load producer orders. Please try again.",
    // Producer Order Details
    "producer.details.backToOrders": "Back to Orders",
    "producer.details.goBack": "Go back",
    "producer.details.title": "Order Details",
    "producer.details.orderNumber": "Order Number",
    "producer.details.date": "Date",
    "producer.details.status": "Status",
    "producer.details.products": "Products",
    "producer.details.sizeEvidence": "Size Evidence Photos",
    "producer.details.viewFullSize": "View Full Size",
    "producer.details.photo": "Photo {index}",
    "producer.details.photosHelp":
      "Customer provided these photos to help you understand their size requirements. Use these as reference when preparing their order.",
    "producer.details.customerNotes": "Customer Notes",
    "producer.details.orderSummary": "Order Summary",
    "producer.details.subtotal": "Subtotal",
    "producer.details.shipping": "Shipping",
    "producer.details.free": "Free",
    "producer.details.total": "Total",
    "producer.details.customerInformation": "Customer Information",
    "producer.details.contactInformation": "Contact Information",
    "producer.details.noEmail": "No email provided",
    "producer.details.noPhone": "No phone provided",
    "producer.details.shippingAddress": "Shipping Address",
    "producer.details.noName": "No name provided",
    "producer.details.updateStatus": "Update Order Status",
    "producer.details.markProcessing": "Mark as Processing",
    "producer.details.markHandled": "Mark as Handled",
    "producer.details.markShipped": "Mark as Shipped",
    "producer.details.markDelivered": "Mark as Delivered",
    "producer.details.confirmedByCustomer": "Order Confirmed by Customer",
    "producer.details.orderDelivered": "Order Delivered",
    "producer.details.confirmedOn": "Confirmed on",
    // Notifications
    "notifications.title": "Notifications",
    "notifications.unread.one": "{count} unread notification",
    "notifications.unread.other": "{count} unread notifications",
    "notifications.none": "No notifications yet",
    "notifications.viewAll": "View All Notifications",
    "notifications.customer": "Customer",
    "notifications.amount": "Amount",
    "notifications.markAsRead": "Mark as read",
    // Admin Dashboard
    "admin.header.title": "System Administration",
    "admin.header.subtitle":
      "Monitor platform activity and manage users, products, and operations",
    "admin.tabs.overview": "overview",
    "admin.tabs.approvals": "approvals",
    "admin.tabs.users": "users",
    "admin.tabs.analytics": "analytics",
    "admin.stats.totalUsers": "Total Users",
    "admin.stats.producers": "Producers",
    "admin.stats.orders": "Orders",
    "admin.stats.revenue": "Revenue",
    "admin.userDistribution": "User Distribution",
    "admin.recentActivity": "Recent Activity",
    "admin.activity.orderDelivered": "Order delivered",
    "admin.activity.orderCancelled": "Order cancelled",
    "admin.activity.orderUpdate": "Order update",
    "admin.roles.producers": "Producers",
    "admin.roles.agents": "Agents",
    "admin.roles.customers": "Customers",
    "admin.producers.title": "Producers ({count})",
    "admin.agents.title": "Agents ({count})",
    "admin.search": "Search",
    "admin.verified": "Verified",
    "admin.pending": "Pending",
    "admin.active": "Active",
    "admin.business": "Business",
    "admin.managedProducers": "Managed Producers",
    "admin.approvals.title": "Pending Approvals ({count})",
    "admin.producer": "Producer",
    "admin.submitted": "Submitted",
  },
  rw: {
    home: "Ahabanza",
    companies: "Ibigo",
    tryOn: "Gerageza",
    products: "Ibicuruzwa",
    cart: "Igikoni",
    profile: "Umwirondoro",
    signIn: "Kwinjira",
    signOut: "Gusohoka",
    browse: "Hitamo",
    myProducts: "Ibicuruzwa Byanjye",
    addProduct: "Ongeraho Igicuruzwa",
    orders: "Orders",
    myOrders: "My Orders",
    myStore: "Iduka Ryanjye",
    subscription: "Ukwiyandikisha",
    productCategories: "Ibyiciro by'Ibicuruzwa",
    usersManagement: "Imicungire y'Abakoresha",
    dashboard: "Ikibaho",
    producersManagement: "Imicungire y'Abakora",
    navigation: "Ihinduranya",
    tools: "Ibikoresho",
    account: "Konti",
    lightMode: "Urumuri",
    darkMode: "Umukara",
    shoppingCart: "Ingoboka yo Gucuruza",
    profileSettings: "Igenamiterere y'Umwirondoro",
    changePassword: "Hindura Ijambobanga",
    active: "Gikora",
    expired: "Yarangiye",
    expiringIn: "Irangira mu",
    walletBalance: "Umubare uri muri Wallet",
    loading: "Birimo Gutangiza...",
    balance: "Umubare",
    manageSubscription: "Tunganya Ukwiyandikisha",
    activeSubscriptionRequired: "Ukwiyandikisha gukora birakenewe",
    needActiveSubscription:
      "Ukeneye ukwiyandikisha gukora kugira ngo ushyiremo ibicuruzwa bishya.",
    activePlan: "Pulisiyo ikora",
    subscriptionInactive: "Ukwiyandikisha kwarangiye cyangwa ntikwemewe",
    productLimitReached: "Umubare w'ibicuruzwa wageze ku rugero",
    planAllowsUpTo_prefix: "Pulisiyo yawe yemera kugeza kuri",
    planAllowsUpTo_suffix:
      "ibicuruzwa. Kuraho bimwe cyangwa uzamure pulisiyo kugira ngo wongereho.",
    newProduct: "Igicuruzwa Gishya",
    createProduct: "Hanga Igicuruzwa",
    productCreatedTitle: "Igicuruzwa cyakozwe neza!",
    productCreatedDesc_prefix: "",
    productCreatedDesc_suffix: " cyoherejwe gusuzumwa.",
    productCreateFailed: "Byanze gukora igicuruzwa",
    goToDashboard: "Jya ku Kibaho",
    upgradePlan: "Zamura Pulisiyo",
    readAgain: "Ongera usome",
    agreeAndContinue: "Nemeye & Komeza",
    confirming: "Kwemeza...",
    version: "Verisiyo",
    updated: "Byavuguruwe",
    agentTermsTitle: "Amasezerano y'Umukozi (Agent)",
    termsScopeOfWork: "Inshingano z'Akazi",
    termsScopeContent:
      "Abakozi bafasha abakora (producers) kwiyandikisha no gutunganya ubwishyu.",
    termsCommissionTitle: "Ijanisha 40%",
    termsCommissionDesc: "Uhembwa kuri buri kwiyandikisha utunganyije",
    termsProfessionalConductTitle: "Imyitwarire y'Umwuga",
    termsProfessionalConductDesc: "Kurikiza amabwiriza n'amategeko y'igihugu",
    acceptTermsFailed: "Byanze kwemera amasezerano. Ongera ugerageze.",
    producerTermsTitle: "Amasezerano y'Ukoresha ku Bacuruzi (Producers)",
    verifiedBusiness: "Ubucuruzi Bwemejwe",
    verifiedBusinessDesc: "Tanga amakuru nyayo y'ukuri ku bwizere n'igaragaza",
    timelyFulfillment: "Kuzuza Ibyo Wasezeranye Ku Gihe",
    timelyFulfillmentDesc: "Emera no kohereza amab订单 ku gihe",
    // Pages
    "privacy.title": "Politiki y’Ibanga",
    "privacy.subtitle":
      "Uko dukusanya, dukoresha, kandi turinda amakuru yawe muri Nyambika.",
    "privacy.section1.title": "1. Amakuru Dukusanya",
    "privacy.section2.title": "2. Uko Dukoresha Amakuru Yawe",
    "privacy.section3.title": "3. Gusangiza Amakuru",
    "privacy.section4.title": "4. Uburenganzira Bwawe & Amahitamo",
    "privacy.section5.title": "5. Umutekano w'Amakuru & Igihe Abikwa",
    "privacy.section6.title": "6. Tuvugishe",
    "privacy.section1.body":
      "Dukusanya amakuru kugira ngo dutange kandi tunoze serivisi zacu, harimo konti, ibikoresho, uko ukoresha urubuga, n'ibyo wohereza (nko amafoto ya AI try‑on). Dukoresha gusa ibikenewe.",
    "privacy.section2.body":
      "Dukoresha amakuru kugira ngo dukore Nyambika, dutange ubunararibonye bwihariye, turinde umutekano kandi twubahirize amategeko.",
    "privacy.section3.body":
      "Ntiducuruza amakuru yawe. Dusangira amakuru gusa n'abatanga serivisi bizerwa b'ingenzi ku mikorere ya platitforme, hubahirizwa ubwirinzi n'ibanga bikwiye.",
    "privacy.section4.item1":
      "Kureba, kuvugurura, cyangwa gusiba amakuru ya konti yawe",
    "privacy.section4.item2": "Gukurura amakuru yawe aho bikwiye",
    "privacy.section4.item3": "Kureka ubutumwa butari ngombwa",
    "privacy.section4.item4": "Igenzura rya cookies muri mushakisho wawe",
    "privacy.section5.body":
      "Dukoresha uburyo bwo hejuru bwo kurinda umutekano. Amakuru abikwa igihe gikenewemo gusa hanyuma agahanagurwa cyangwa akagirwa ibanga.",
    "privacy.section6.body":
      "Ibibazo ku ibanga twoherereza kuri privacy@nyambika.com.",
    "terms.title": "Amasezerano yo Gukoresha",
    "terms.subtitle": "Amategeko n’amabwiriza yo gukoresha Nyambika.",
    "terms.body.intro":
      "Aya masezerano agenga uko ukoresha Nyambika. Ukoresheje serivisi zacu, uba wemeye aya masezerano.",
    "terms.section1.title": "1. Kwemera Amasezerano",
    "terms.section2.title": "2. Uko Ukoresha Serivisi",
    "terms.section3.title": "3. AI Try‑On n'Ibikubiyemo",
    "terms.section4.title": "4. Amasezerano y'Ibicuruzwa n'Itegeko",
    "terms.section5.title": "5. Inshingano n'Imbibi",
    "terms.section6.title": "6. Impinduka ku Masezerano",
    "terms.section7.title": "7. Twandikire",
    "cookies.title": "Politiki ya Cookies",
    "cookies.subtitle":
      "Uko dukoresha cookies kugira ngo tunoze uburyo ukoresha urubuga.",
    "cookies.body.intro":
      "Dukoresha cookies ku buryo tubika amahitamo yawe no kunoza umuvuduko.",
    "cookies.section1.title": "1. Cookies ni iki?",
    "cookies.section2.title": "2. Ubwoko bwa Cookies dukoresha",
    "cookies.section3.title": "3. Uko wayobora Cookies",
    "cookies.section4.title": "4. Tuvugishe",
    "cookies.section1.body":
      "Cookies ni dosiye nto zibikwa kuri mudasobwa yawe kugirango zibuke amahitamo kandi zinonosore imikorere. Dukoresha na local storage na pixels.",
    "cookies.section2.item1":
      "By'ingenzi: bikenewe ku mikorere (kwinjira, igikapu, kugendagenda)",
    "cookies.section2.item2":
      "Imikorere: idufasha kumenya uko ukoresha no kunoza",
    "cookies.section2.item3":
      "Amahitamo: yibuka insanganyamatsiko yawe, ururimi, n'igenamiterere",
    "cookies.section2.item4":
      "Isesengura: gufasha gupima uko abantu bitabira n'ubwiza",
    "cookies.section3.body":
      "Ushobora kugenzura cookies muri igenamiterere rya mushakisho wawe. Guhagarika bimwe bishobora kugira ingaruka ku mikorere.",
    "cookies.section4.body":
      "Kubibazo kuri politiki, twoherereza kuri privacy@nyambika.com.",
    "about.title": "Ibyerekeye Nyambika",
    "about.subtitle":
      "Turimo kubaka urubuga rw’imyenda rufashijwe na AI mu Rwanda.",
    "about.body.intro":
      "Nyambika ifasha abaguzi n'abakora ibisubizo bya AI try-on, amaduka, n'isesengura.",
    "about.mission": "Intego",
    "about.whatWeDo": "Ibyo Dukora",
    "about.values": "Indangagaciro",
    "about.mission.body":
      "Guteza imbere urwego rw’imyenda mu Rwanda hifashishijwe ikoranabuhanga rya AI, gufasha abaguzi kureba imyambarire ako kanya no gufasha abakora kugera ku bakiriya byoroshye.",
    "about.whatWeDo.item1": "AI Try‑On yo kwerekana uko bihuye ako kanya",
    "about.whatWeDo.item2": "Isoko rya kijyambere ry'Abakora bo mu gihugu",
    "about.whatWeDo.item3": "Guhitamo no gushakisha by'umwihariko",
    "about.whatWeDo.item4": "Gutanga amab订单 byoroshye n'ibibaho by'abakora",
    "about.values.item1": "Ubuzima bwite & icyizere",
    "about.values.item2": "Ingaruka zishingiye ku b'iwacu",
    "about.values.item3": "Urusobe & Uburangare",
    "about.values.item4": "Ubuziranenge n'ubuhanga",
    "about.getInTouch": "Tuvugishe",
    "about.quickStats": "Imibare y'Incamake",
    "contact.title": "Tuvugishe",
    "contact.subtitle":
      "Twishimiye ubutumwa bwawe. Twohereze ubutumwa tugusubize vuba.",
    "contact.body.intro":
      "Kubaza cyangwa gusaba ubufasha, tuvugishe kandi tuzahita dusubiza.",
    // Home
    "home.brands": "Ibigo",
    "home.shopByCategory": "Gura bitewe n'Icyiciro",
    "home.trending": "Ibicuruzwa biri ku Isonga",
    "home.hot": "Bishyushye",
    "home.moreTitle": "Hari Ibindi Bicuruza byinshi!",
    "home.moreDesc.prefix": "Reba",
    "home.moreDesc.suffix":
      "+ ibicuruzwa byinshi muri kolekisiyo yuzuye. Shaka ihitamo rikwiye!",
    "home.browseAll": "Reba Ibicuruzwa Byose",
    "home.advancedSearch":
      "Gushakisha byimbitse n'ayandi mafunguro yo gushungura",
    "home.noProducts": "Nta bicuruzwa bibonetse",
    "home.noProductsDesc":
      "Nta bicuruzwa bihuye n'ibyo wasabye. Gerageza guhindura amasezerano yo gushungura.",
    "home.clearFilters": "Siba Amashungura",
    "home.products": "Ibicuruzwa",
    "home.items": "ibicuruzwa",
    // Products Search
    "search.title": "Shakisha Ibicuruzwa",
    "search.subtitle":
      "Shaka ibicuruzwa byiza ukoresheje gushakisha bufashijwe na AI ✨",
    "search.searchingFor": "Turimo gushakisha",
    "search.allProducts": "Ibicuruzwa Byose",
    "search.browseAll": "Reba byose",
    "search.items": "ibicuruzwa",
    "search.products": "ibicuruzwa",
    "search.product": "igicuruzwa",
    "search.category": "Icyiciro",
    "search.showing": "Twerekana",
    "search.noProducts": "Nta bicuruzwa bibonetse",
    "search.noProductsFor": "Nta bicuruzwa twabonye bihuye na",
    "search.tryAdjust": "Gerageza guhindura uko ushakisha cyangwa amashungura.",
    "search.noProductsInCategory": "Nta bicuruzwa biri muri iki cyiciro.",
    "search.clearFilters": "Siba amashungura",
    "search.loadMore": "Komeza Urebe",
    "search.loadMoreProducts": "Komeza Urebe Ibicuruzwa",
    "search.loading": "Birahabwa...",
    "search.loadingMore": "Gukomeza Guhabwa ibicuruzwa...",
    "search.sort.newest": "Ibiheruka Byambere",
    "search.sort.popular": "Bikunzwe cyane",
    "search.sort.priceAsc": "Igiciro: Gito kujya hejuru",
    "search.sort.priceDesc": "Igiciro: Hejuru kujya hasi",
    "search.error.title": "Habaye Ikosa",
    "search.error.message":
      "Ntitwabashije kwakira ibicuruzwa. Ongera ugerageze.",
    "search.error.retry": "Ongera ugerageze",
    // Product Details
    "product.linkCopiedTitle": "Ihuza ryakoporowe",
    "product.linkCopiedDesc": "Ihuza ry'igicuruzwa ryakoporowe.",
    "product.deleted": "Byasabwe",
    "product.deletedDesc": "Igicuruzwa cyasibwe neza.",
    "product.deleteFailed": "Gusiba byanze",
    "product.deleteConfirm":
      "Gusiba iki gicuruzwa? Ntibishobora gusubizwa inyuma.",
    "product.sizeRequired": "Ingano Ikenewwe",
    "product.selectSizeFirst": "Hitamo ingano mbere na mbere",
    "product.colorRequired": "Ibara Rikenewe",
    "product.selectColorFirst": "Hitamo ibara mbere na mbere",
    "product.addedToCart": "Byongewe mu gikapu",
    "product.addedToCartDesc": "Igicuruzwa cyongewe mu gikapu cyawe",
    "product.notFound": "Igicuruzwa Nticyabonetse",
    "product.backToProducts": "Subira ku Bicuruza",
    "product.back": "Subira",
    "product.details": "Ibisobanuro by'Igicuruzwa",
    "product.share": "Sangira",
    "product.edit": "Hindura igicuruzwa",
    "product.boost": "Teza imbere igicuruzwa",
    "product.delete": "Siba igicuruzwa",
    "product.aiReady": "AI Yiteguye",
    "product.inStock": "✓ Kirahari",
    "product.outOfStock": "Cyashize",
    // Footer
    "footer.liveBadge": "AI iri kuri ligne",
    "footer.tryOutfits": "Gerageza imyambaro mu buryo bwa virituali",
    "footer.ctaTitle": "Gerageza AI Try‑On ku Mwambarire Yawe Ikurikira",
    "footer.ctaDesc":
      "Shyiraho ifoto yawe, ubone ihitamo rya kijyambere ako kanya, ugure wizeye ukoresheje AI ya Nyambika.",
    "footer.startTryOn": "Tangira AI Try‑On",
    "footer.browseProducts": "Reba Ibicuruzwa",
    "footer.brandTagline":
      "Urubuga rw'imideli rufashijwe na AI ku isoko ry'imyenda mu Rwanda. Shakisha, gerageza, kandi ugure ku bakora bo mu gihugu.",
    "footer.stayUpdated": "Komeza Umenyeshwa",
    "footer.subscribeDesc":
      "Iyandikishe ubone ibishya byagezeho, amakuru n'ubwiganze bw'ibiciro.",
    "footer.invalidEmailTitle": "Imeli si yo",
    "footer.invalidEmailDesc": "Shyiraho aderesi ya imeli yemewe.",
    "footer.alreadySubscribed": "Ubusanzwe wanditswe",
    "footer.alreadySubscribedDesc":
      "Uri mu bantu bohererezwa amakuru. Urakoze!",
    "footer.subscribed": "Wiyandikishije",
    "footer.subscribedDesc": "Urakoze kwiyandikisha kuri newsletter!",
    "footer.subscriptionFailed": "Kwiyandikisha byanze",
    "footer.subscriptionFailedDesc": "Ongera ugerageze nyuma.",
    "footer.emailPlaceholder": "Shyiramo imeli yawe",
    "footer.emailAria": "Aderesi ya imeli",
    "footer.subscribing": "Birimo Kwiyandikisha...",
    "footer.subscribe": "Iyandikishe",
    "footer.chatWhatsApp": "Vugana kuri WhatsApp",
    "footer.phone": "+250 782 634 364",
    "footer.email": "info@nyambika.com",
    "footer.location": "Kigali, Rwanda",
    "footer.backToTop": "Subira hejuru",
    "footer.link.home": "Ahabanza",
    "footer.link.products": "Ibicuruzwa",
    "footer.link.tryOn": "AI Try‑On",
    "footer.link.profile": "Umwirondoro",
    "footer.link.about": "Ibyerekeye",
    "footer.link.contact": "Tuvugishe",
    "footer.link.privacy": "Politiki y'Ibanga",
    "footer.link.terms": "Amasezerano",
    "footer.link.cookies": "Cookies",
    "footer.copyright": "© {year} Nyambika.",
    "footer.allRights": "Uburenganzira bwose burabitswe.",
  },
  fr: {
    home: "Accueil",
    companies: "Entreprises",
    tryOn: "Essayer",
    products: "Produits",
    cart: "Panier",
    profile: "Profil",
    signIn: "Se connecter",
    signOut: "Se déconnecter",
    browse: "Parcourir",
    myProducts: "Mes Produits",
    addProduct: "Ajouter un produit",
    orders: "Commandes",
    myOrders: "Mes Commandes",
    myStore: "Ma Boutique",
    subscription: "Abonnement",
    productCategories: "Catégories de produits",
    usersManagement: "Gestion des utilisateurs",
    dashboard: "Tableau de bord",
    producersManagement: "Gestion des producteurs",
    navigation: "Navigation",
    tools: "Outils",
    account: "Compte",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    shoppingCart: "Panier",
    profileSettings: "Paramètres du profil",
    changePassword: "Changer le mot de passe",
    active: "Actif",
    expired: "Expiré",
    expiringIn: "Expire dans",
    walletBalance: "Solde du portefeuille",
    loading: "Chargement...",
    balance: "Solde",
    manageSubscription: "Gérer l'abonnement",
    activeSubscriptionRequired: "Abonnement actif requis",
    needActiveSubscription:
      "Vous avez besoin d'un abonnement actif pour créer de nouveaux produits.",
    activePlan: "Offre active",
    subscriptionInactive: "Abonnement expiré ou inactif",
    productLimitReached: "Limite de produits atteinte",
    planAllowsUpTo_prefix: "Votre offre actuelle permet jusqu'à",
    planAllowsUpTo_suffix:
      "produits. Veuillez en supprimer ou mettre à niveau pour en ajouter davantage.",
    newProduct: "Nouveau Produit",
    createProduct: "Créer le produit",
    productCreatedTitle: "Produit créé avec succès !",
    productCreatedDesc_prefix: "",
    productCreatedDesc_suffix: " a été soumis pour approbation.",
    productCreateFailed: "Échec de création du produit",
    goToDashboard: "Aller au Tableau de bord",
    upgradePlan: "Mettre à niveau",
    readAgain: "Relire",
    agreeAndContinue: "J'accepte et je continue",
    confirming: "Confirmation...",
    version: "Version",
    updated: "Mis à jour",
    agentTermsTitle: "Conditions de l'Agent",
    termsScopeOfWork: "Champ d'application",
    termsScopeContent:
      "Les agents aident les producteurs à s'abonner et à traiter les paiements.",
    termsCommissionTitle: "Commission de 40%",
    termsCommissionDesc: "Gagnez sur chaque abonnement que vous traitez",
    termsProfessionalConductTitle: "Conduite Professionnelle",
    termsProfessionalConductDesc:
      "Respectez les politiques et les réglementations locales",
    acceptTermsFailed:
      "Échec de l'acceptation des conditions. Veuillez réessayer.",
    // Pages
    "privacy.title": "Politique de Confidentialité",
    "privacy.subtitle":
      "Découvrez comment nous collectons, utilisons et protégeons vos données.",
    "privacy.section1.title": "1. Informations que nous collectons",
    "privacy.section2.title": "2. Comment nous utilisons vos informations",
    "privacy.section3.title": "3. Partage des données",
    "privacy.section4.title": "4. Vos droits et choix",
    "privacy.section5.title": "5. Sécurité et conservation des données",
    "privacy.section6.title": "6. Contactez-nous",
    "privacy.section1.body":
      "Nous collectons des informations pour fournir et améliorer nos services, notamment les détails de compte, les informations sur l'appareil, les données d'utilisation et le contenu que vous téléchargez (par ex. photos pour l'essayage IA). Nous minimisons la collecte et ne conservons que le nécessaire.",
    "privacy.section2.body":
      "Nous utilisons les données pour faire fonctionner Nyambika, offrir des expériences personnalisées, assurer la sécurité et respecter les obligations légales.",
    "privacy.section3.body":
      "Nous ne vendons pas vos informations personnelles. Nous partageons les données uniquement avec des prestataires et partenaires de confiance nécessaires au fonctionnement de la plateforme (hébergement, analytics, paiement, CDN), sous des mesures strictes de confidentialité et sécurité.",
    "privacy.section4.item1": "Accéder, mettre à jour ou supprimer vos données",
    "privacy.section4.item2": "Télécharger vos données lorsque applicable",
    "privacy.section4.item3": "Refuser les communications non essentielles",
    "privacy.section4.item4": "Contrôler les cookies dans votre navigateur",
    "privacy.section5.body":
      "Nous utilisons des pratiques de sécurité conformes aux normes du secteur. Les données sont conservées uniquement le temps nécessaire puis supprimées ou anonymisées.",
    "privacy.section6.body":
      "Pour les questions de confidentialité, contactez-nous à privacy@nyambika.com.",
    "terms.title": "Conditions d’Utilisation",
    "terms.subtitle": "Les règles et conditions d'utilisation de Nyambika.",
    "terms.body.intro":
      "Ces conditions régissent votre utilisation de Nyambika. En utilisant nos services, vous acceptez ces conditions.",
    "terms.section1.title": "1. Acceptation des Conditions",
    "terms.section2.title": "2. Utilisation du Service",
    "terms.section3.title": "3. Essayage IA et Contenu",
    "terms.section4.title": "4. Commandes et Marketplace",
    "terms.section5.title": "5. Avertissements et Responsabilité",
    "terms.section6.title": "6. Modifications des Conditions",
    "terms.section7.title": "7. Contact",
    "cookies.title": "Politique des Cookies",
    "cookies.subtitle":
      "Comment nous utilisons les cookies pour améliorer votre expérience.",
    "cookies.body.intro":
      "Nous utilisons des cookies pour mémoriser vos préférences et améliorer les performances.",
    "cookies.section1.title": "1. Que sont les cookies ?",
    "cookies.section2.title": "2. Types de cookies que nous utilisons",
    "cookies.section3.title": "3. Gérer les cookies",
    "cookies.section4.title": "4. Contact",
    "about.title": "À propos de Nyambika",
    "about.subtitle":
      "Nous construisons la plateforme de mode alimentée par l’IA pour le Rwanda.",
    "about.body.intro":
      "Nyambika permet aux acheteurs et producteurs d'utiliser l'essayage IA, des boutiques et des analyses.",
    "about.mission": "Mission",
    "about.whatWeDo": "Ce que nous faisons",
    "about.values": "Valeurs",
    "about.mission.body":
      "Dynamiser l'écosystème de la mode au Rwanda grâce à l'IA, permettant aux consommateurs de visualiser instantanément les styles et aidant les producteurs à atteindre leurs clients efficacement.",
    "about.whatWeDo.item1": "Essayage IA pour visualisation instantanée",
    "about.whatWeDo.item2": "Marketplace moderne pour les producteurs locaux",
    "about.whatWeDo.item3": "Recommandations et recherche personnalisées",
    "about.whatWeDo.item4":
      "Commandes fluides et tableaux de bord pour producteurs",
    "about.values.item1": "Confidentialité & confiance",
    "about.values.item2": "Impact local d'abord",
    "about.values.item3": "Inclusivité & accessibilité",
    "about.values.item4": "Qualité et savoir‑faire",
    "about.getInTouch": "Nous contacter",
    "about.quickStats": "Chiffres clés",
    "contact.title": "Nous contacter",
    "contact.subtitle":
      "Envoyez-nous un message et notre équipe vous répondra rapidement.",
    "contact.body.intro":
      "Pour toute question ou demande, contactez notre équipe et nous répondrons rapidement.",
    // Home
    "home.brands": "Stories des Marques",
    "home.shopByCategory": "Acheter par Catégorie",
    "home.trending": "Produits Tendance",
    "home.hot": "CHAUD",
    "home.moreTitle": "Encore plus de super produits !",
    "home.moreDesc.prefix": "Découvrez",
    "home.moreDesc.suffix":
      "+ autres produits incroyables dans notre collection. Trouvez votre style idéal !",
    "home.browseAll": "Parcourir tous les produits",
    "home.advancedSearch": "Recherche avancée et filtres disponibles",
    "home.noProducts": "Aucun produit trouvé",
    "home.noProductsDesc":
      "Nous n'avons trouvé aucun produit correspondant à vos critères. Essayez d'ajuster vos filtres.",
    "home.clearFilters": "Effacer les filtres",
    "home.products": "Produits",
    "home.items": "articles",
    // Products Search
    "search.title": "Découvrir des Produits",
    "search.subtitle":
      "Trouvez des produits incroyables avec la recherche IA ✨",
    "search.searchingFor": "Recherche de",
    "search.allProducts": "Tous les Produits",
    "search.browseAll": "Tout parcourir",
    "search.items": "articles",
    "search.products": "produits",
    "search.product": "produit",
    "search.category": "Catégorie",
    "search.showing": "Affichage",
    "search.noProducts": "Aucun produit trouvé",
    "search.noProductsFor": "Nous n'avons trouvé aucun produit correspondant à",
    "search.tryAdjust": "Essayez d'ajuster votre recherche ou vos filtres.",
    "search.noProductsInCategory": "Aucun produit dans cette catégorie.",
    "search.clearFilters": "Effacer les filtres",
    "search.loadMore": "Charger Plus",
    "search.loadMoreProducts": "Charger Plus de Produits",
    "search.loading": "Chargement...",
    "search.loadingMore": "Chargement de plus de produits...",
    "search.sort.newest": "Les plus récents",
    "search.sort.popular": "Les plus populaires",
    "search.sort.priceAsc": "Prix : du plus bas au plus élevé",
    "search.sort.priceDesc": "Prix : du plus élevé au plus bas",
    "search.error.title": "Une erreur s'est produite",
    "search.error.message":
      "Impossible de charger les produits. Veuillez réessayer.",
    "search.error.retry": "Réessayer",
    // Product Details
    "product.linkCopiedTitle": "Lien copié",
    "product.linkCopiedDesc": "Lien du produit copié dans le presse-papiers.",
    "product.deleted": "Supprimé",
    "product.deletedDesc": "Produit supprimé avec succès.",
    "product.deleteFailed": "Échec de la suppression",
    "product.deleteConfirm":
      "Supprimer ce produit ? Cette action est irréversible.",
    "product.sizeRequired": "Taille requise",
    "product.selectSizeFirst": "Veuillez d'abord sélectionner une taille",
    "product.colorRequired": "Couleur requise",
    "product.selectColorFirst": "Veuillez d'abord sélectionner une couleur",
    "product.addedToCart": "Ajouté au panier",
    "product.addedToCartDesc": "Produit ajouté à votre panier",
    "product.notFound": "Produit introuvable",
    "product.backToProducts": "Retour aux produits",
    "product.back": "Retour",
    "product.details": "Détails du Produit",
    "product.share": "Partager",
    "product.edit": "Modifier le produit",
    "product.boost": "Booster le produit",
    "product.delete": "Supprimer le produit",
    "product.aiReady": "Prêt pour l'IA",
    "product.inStock": "✓ En Stock",
    "product.outOfStock": "Rupture de stock",
    // Footer
    "footer.liveBadge": "IA en direct",
    "footer.tryOutfits": "Essayez des tenues virtuellement",
    "footer.ctaTitle": "Essayez les tenues avec l'IA pour votre prochain look",
    "footer.ctaDesc":
      "Téléchargez votre photo, obtenez des tenues intelligentes instantanément et achetez en toute confiance avec l'IA de Nyambika.",
    "footer.startTryOn": "Commencer l'Essayage IA",
    "footer.browseProducts": "Parcourir les Produits",
    "footer.brandTagline":
      "Plateforme de mode alimentée par l'IA pour le secteur de l'habillement au Rwanda. Découvrez, essayez et achetez auprès des producteurs locaux.",
    "footer.stayUpdated": "Restez informé",
    "footer.subscribeDesc":
      "Abonnez-vous pour recevoir les nouveautés, mises à jour et offres spéciales.",
    "footer.invalidEmailTitle": "E-mail invalide",
    "footer.invalidEmailDesc": "Veuillez saisir une adresse e-mail valide.",
    "footer.alreadySubscribed": "Déjà abonné",
    "footer.alreadySubscribedDesc": "Vous êtes déjà sur notre liste. Merci !",
    "footer.subscribed": "Abonnement confirmé",
    "footer.subscribedDesc": "Merci de vous être abonné à notre newsletter !",
    "footer.subscriptionFailed": "Échec de l'abonnement",
    "footer.subscriptionFailedDesc": "Veuillez réessayer plus tard.",
    "footer.emailPlaceholder": "Entrez votre e-mail",
    "footer.emailAria": "Adresse e-mail",
    "footer.subscribing": "Abonnement en cours...",
    "footer.subscribe": "S'abonner",
    "footer.chatWhatsApp": "Discuter sur WhatsApp",
    "footer.phone": "+250 782 634 364",
    "footer.email": "info@nyambika.com",
    "footer.location": "Kigali, Rwanda",
    "footer.backToTop": "Haut de page",
    "footer.link.home": "Accueil",
    "footer.link.products": "Produits",
    "footer.link.tryOn": "Essayage IA",
    "footer.link.profile": "Profil",
    "footer.link.about": "À propos",
    "footer.link.contact": "Contact",
    "footer.link.privacy": "Confidentialité",
    "footer.link.terms": "Conditions",
    "footer.link.cookies": "Cookies",
    "footer.copyright": "© {year} Nyambika.",
    "footer.allRights": "Tous droits réservés.",
  },
};

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>("en");
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    // Get language from localStorage after component mounts
    const saved = localStorage.getItem("nyambika-language");
    if (saved && (saved === "en" || saved === "rw" || saved === "fr")) {
      setLanguageState(saved as Language);
    }
  }, []);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    if (isClient) {
      localStorage.setItem("nyambika-language", newLanguage);
    }
  };

  const t = (key: string): string => {
    const current =
      translations[language][
        key as keyof (typeof translations)[typeof language]
      ];
    if (current) return current as string;
    const fallback = translations.en[key as keyof typeof translations.en];
    return (fallback as string) || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
